export const perfumesMasculinos = [
  {
    brand: "Creed",
    name: "Aventus",
    tags: ["Noite", "Versátil"],
    notes: "Abacaxi · Amadeirado · Almíscar",
    score: "9.2",
    dupe: "CDNIM — Armaf",
  },
  {
    brand: "Dior",
    name: "Sauvage Elixir",
    tags: ["Noite", "Frio"],
    notes: "Ambroxan · Especiado",
    score: "9.0",
    dupe: "Asad — Lattafa",
  },
  {
    brand: "MFK",
    name: "Baccarat Rouge",
    tags: ["Versátil"],
    notes: "Âmbar · Jasmim",
    score: "9.2",
    dupe: "Amber Oud",
  },
  {
    brand: "PdM",
    name: "Layton",
    tags: ["Frio"],
    notes: "Baunilha · Maçã",
    score: "9.1",
    dupe: "Detour Noir",
  },
  {
    brand: "Chanel",
    name: "Bleu de Chanel",
    tags: ["Dia"],
    notes: "Cítrico · Amadeirado",
    score: "8.9",
    dupe: "Blue Iconic",
  },
  {
    brand: "Dior",
    name: "Dior Homme",
    tags: ["Elegante"],
    notes: "Íris · Amadeirado",
    score: "9.0",
    dupe: "Dark Door",
  },
];
